Contact form added in this milestone.
Mahdi-Niazi/Portfolio_Mobile_Setup pull request #3
Opened 2023-06-06 12:18 UTC by Mahdi-Niazi

In this milestone I:

- Add Contact form to index.html form
- design the contact form based on figma template
- Add CSS property to the style.css file for contact form.

2023-06-06 12:25 UTC, TuyishimireEric commented
# INVALID ❌ ❌ ❌
### Hi @Mahdi-Niazi   👋

While you made a great effort in this project, I can't go ahead and review your code.

## Invalid Code Review Request ❌
This is a pair-programming project and I only see in the commit history only one contributor 😨, Kindly collaborate with your coding partner and submit again once you are done 🙏  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Kindly create  a new PR that follows the Gitflow approach

Cheers, and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

---
_Invalid Code Review Request does not count into the code reviews limit._

2023-06-06 14:01 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi Team 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

[REQUIRED] - I'm unable to add an inline comment to your readme, please check the requested change below

![image](https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/78251927/7caa35c6-4801-4d22-aff7-20ddc8192d86)

![image](https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/78251927/141cab44-679b-426f-8176-5a5947133838)

Kindly fix the broken link to your LinkedIn profile, let's avoid broken links in our readme for a professional repository. 🤗👍

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 14:01 UTC, abdulhamiid commented on index.html
> +            <textarea name="message" id="message" rows="10" cols="20" maxlength="500" placeholder="Write me something..."></textarea>
According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md), kindly ensure that a user cannot submit the form if one or more of the fields is empty. 💪

2023-06-06 14:01 UTC, abdulhamiid commented on index.html
> +        </form>
According to the project requirements, it is important that we stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

Kindly implement the button interactions such as hover, active (when the button is pressed), disabled, and enable (default state) styled as shown in the Figma template. 🤗🛠

![image](https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/78251927/8e9ffad4-0825-4a21-9343-f7b58535aa00)

2023-06-06 14:01 UTC, abdulhamiid commented on index.html
> +            <textarea name="message" id="message" rows="10" cols="20" maxlength="500" placeholder="Write me something..."></textarea>
Figma
![image](https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/78251927/4e7c9299-85cb-40b7-a7c2-84762427f0d8)

Your design
![image](https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/78251927/ec6ff7a5-fbf4-468e-b4e8-a5eb2d28a5c8)

I would suggest that we reduce the Form margin (right & left) to stick to the design on Figma as much as possible. 🤗 part of our learning objective is to understand how to parse a Figma design to create a UI. 💪

2023-06-06 14:01 UTC, abdulhamiid commented on index.html
>  </body>
According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md), the section you need to build for this milestone is:
- the contact form:
- and the footer (if present in the design)

Kindly add the Footer, following the template that you chose. 🤓🛠

Figma
![image](https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/78251927/01c99302-d566-422b-8ed2-a8c315ab5b87)

2023-06-06 16:14 UTC, stanleySimeon requested changes
# Hi @Mahdi-Niazi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media2.giphy.com/media/vQGBDTkhtIunaJYmRF/giphy-downsized.gif?cid=29caca75sf3uq9y4qgulk5ybbojwg94b4zo6temfzeel417x&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g
)

 ## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 16:14 UTC, stanleySimeon commented on index.html
> +            <textarea name="message" id="message" rows="10" cols="20" maxlength="500" placeholder="Write me something..."></textarea>
As mentioned by the previous reviewer kindly, I suggest that we reduce the Form margin (right & left) to stick to the design on Figma as much as possible. 🤗 part of our learning objective is to understand how to parse a Figma design to create a UI. 💪

> ## The Figma Design
>
><img width="336" alt="Screenshot 2023-06-06 at 12 02 45 PM" src="https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/91237525/c11d9603-382b-4831-be47-e5b851268d7b">
>
> ## Your design
>
><img width="376" alt="Screenshot 2023-06-06 at 11 54 59 AM" src="https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/91237525/b83b6c6e-b836-4deb-b0eb-2c9eebc570d6">

2023-06-06 16:14 UTC, stanleySimeon commented on index.html
>  </body>
Great work on implementing the changes required by the previous reviewer, but there is still something you'll need to fix to go through the next step, kindly I suggest you stick to the design as much as possible `(e.g., font, colors, images, text, margins)` using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

> ## The Figma Design
>
><img width="333" alt="Screenshot 2023-06-06 at 12 11 02 PM" src="https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/91237525/06c00dbf-ddfe-453c-be50-869f3159e1f6">
>
> ## Your Design
>
><img width="376" alt="Screenshot 2023-06-06 at 11 57 37 AM" src="https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/91237525/5f0855c0-0886-4b8e-9f82-c6290e8019d7">

2023-06-07 10:49 UTC, topeogunleye approved these changes
### Hi @Mahdi-Niazi, @s2jack, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- Reduced the Form margin (right & left) to stick to the design on Figma as much as possible. ✔️ 
- All linters are passing :heavy_check_mark: 
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
<img width="292" alt="image" src="https://github.com/Mahdi-Niazi/Portfolio_Mobile_Setup/assets/52934128/6eb6b5b6-46c3-47c7-9516-3fa843c0a4b0">

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 10:52 UTC, merged